database:
  host: localhost
  port: 3306
  name: database
  user: root
  password: password

elo-on-win: 15
elo-on-lose: 20

maximum-elo-difference: 200
time-to-accept: 30 # en secondes
time-before-battle: 5 # en secondes

fight-location:
    world: world
    x: 0
    y: 0
    z: 0
    pitch: 0
    yaw: 0

ranks:
  bronze:
    name: "&7Bronze"
    elo: 0
  silver:
    name: "&fSilver"
    elo: 200
  gold:
    name: "&6Gold"
    elo: 400
  platine:
    name: "&bPlatine"
    elo: 600
  saphir:
    name: "&3Saphir"
    elo: 800
  diamant:
    name: "&dDiamant"
    elo: 1000
  diamant1:
    name: "&dDiamant I"
    elo: 1500
  diamant2:
    name: "&dDiamant II"
    elo: 2000
  diamant3:
    name: "&dDiamant III"
    elo: 2500