name: "PixelQilinRanked"
version: '${version}'
main: fr.pixelqilin.pixelqilinranked.PixelQilinRanked
api-version: 1.16
authors: [ Ordwen ]
depend:
  - "Multiverse-Core"
commands:
  ranked:
    description: default player command
    permission: pixelqilinranked.ranked
    aliases:
      - rq